// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{

	a[0] = "head_tf141_desert_a";
	a[1] = "head_tf141_desert_b";
	a[2] = "head_tf141_desert_c";
	a[3] = "head_tf141_desert_d";
	if(getdvar("mapname")=="favela")
	{
	a[4] = "head_hero_ghost_soccom";
	a[5] = "head_hero_soap_soccom_a";
	}

	return a;
}
